language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .
    - pytest -v
    after_success:
    - pytest --cov
    - coveralls
# just saving travis-ci resources
#  - os: osx
#    language: minimal
#    install: pip3 install -e .[tests]

install: pip install -e .[tests]

script: pytest -rsv
